name: sam2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nifty >=1.2.3
  - imagecodecs
  - magicgui
  - napari >=0.5.0,<0.6.0
  - natsort
  - pip
  - pooch
  - pyside2
  - python-xxhash
  - python-elf >=0.6.1
  - pytorch =*=cpu*
  - torchvision
  - torch_em >=0.7.8
  - tqdm
  - timm
  - xarray <2025.3.0
  - segment-anything 
  - pip:
      - git+https://github.com/ChaoningZhang/MobileSAM.git